ureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true  # The Eureka server itself should not register with another Eureka instance
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
